import { AspectRatioOption, LogoConfig, SlideItem, TypographyConfig } from '../types';
import imgCreativity from '../assets/images/card_studio_creativity_1790459712154.jpg';
import imgArchitecture from '../assets/images/card_minimal_architecture_1790459725529.jpg';
import imgNature from '../assets/images/card_serene_nature_1790459734331.jpg';
import imgCraft from '../assets/images/card_design_craft_1790459743674.jpg';
import imgStructure from '../assets/images/card_modern_structure_1790459754325.jpg';
import imgSkyline from '../assets/images/card_golden_skyline_1790459764376.jpg';

export const PRESET_IMAGES = {
  creativity: imgCreativity,
  architecture: imgArchitecture,
  nature: imgNature,
  craft: imgCraft,
  structure: imgStructure,
  skyline: imgSkyline,
};

export const ASPECT_RATIOS: AspectRatioOption[] = [
  {
    id: '1:1',
    label: 'Carré (1:1)',
    sublabel: '1080 × 1080 px',
    width: 1080,
    height: 1080,
    iconName: 'Square',
    platforms: ['Instagram Feed', 'LinkedIn Post', 'Facebook'],
  },
  {
    id: '9:16',
    label: 'Story / Reel (9:16)',
    sublabel: '1080 × 1920 px',
    width: 1080,
    height: 1920,
    iconName: 'Smartphone',
    platforms: ['Instagram Stories', 'Reels', 'TikTok', 'Shorts'],
  },
  {
    id: '4:5',
    label: 'Portrait Feed (4:5)',
    sublabel: '1080 × 1350 px',
    width: 1080,
    height: 1350,
    iconName: 'RectangleVertical',
    platforms: ['Instagram Portrait', 'LinkedIn Feed'],
  },
  {
    id: '16:9',
    label: 'Paysage (16:9)',
    sublabel: '1920 × 1080 px',
    width: 1920,
    height: 1080,
    iconName: 'Monitor',
    platforms: ['X / Twitter', 'LinkedIn Banner', 'YouTube'],
  },
  {
    id: '2:3',
    label: 'Éditorial (2:3)',
    sublabel: '1000 × 1500 px',
    width: 1000,
    height: 1500,
    iconName: 'Maximize2',
    platforms: ['Pinterest Pin', 'Affiche'],
  },
];

export const PREDEFINED_LOGOS = [
  {
    id: 'studio-minimal',
    name: 'Studio Minimal',
    iconType: 'sparkles',
    defaultText: 'STUDIO HORIZON',
    defaultHandle: '@studio.horizon',
  },
  {
    id: 'aura-crest',
    name: 'Aura Crest',
    iconType: 'compass',
    defaultText: 'AURA COLLECTIVE',
    defaultHandle: '@auracollective',
  },
  {
    id: 'bold-monogram',
    name: 'Modern Bold',
    iconType: 'shield',
    defaultText: 'VALOR MEDIA',
    defaultHandle: '@valormedia',
  },
  {
    id: 'clean-mark',
    name: 'Clean Geometric',
    iconType: 'hexagon',
    defaultText: 'NEXUS DESIGN',
    defaultHandle: '@nexus.design',
  },
];

export const INITIAL_SLIDES: SlideItem[] = [
  {
    id: 'slide-1',
    number: 1,
    text: "La créativité n'est pas un don rare, c'est une façon audacieuse de regarder le monde.",
    kicker: 'VISION & CRÉATION',
    subtitle: 'Épisode 01 · Studio Journal',
    imageUrl: PRESET_IMAGES.creativity,
    imageAlt: 'Studio design avec lumière naturelle',
    imageZoom: 1,
    imageBrightness: 100,
    customOverlayOpacity: 0.45,
    scheduledTime: '2026-09-28T09:00',
  },
  {
    id: 'slide-2',
    number: 2,
    text: "Chaque grand accomplissement commence par une seule idée exécutée avec discipline.",
    kicker: 'MINDSET & EXECUTION',
    subtitle: 'Épisode 02 · Studio Journal',
    imageUrl: PRESET_IMAGES.architecture,
    imageAlt: 'Pavillon architectural minimaliste à l aube',
    imageZoom: 1,
    imageBrightness: 100,
    customOverlayOpacity: 0.45,
    scheduledTime: '2026-09-29T12:30',
  },
  {
    id: 'slide-3',
    number: 3,
    text: "La régularité bat l'intensité chaque jour de la semaine sans exception.",
    kicker: 'RÈGLE D OR',
    subtitle: 'Épisode 03 · Studio Journal',
    imageUrl: PRESET_IMAGES.nature,
    imageAlt: 'Lac alpin brumeux au lever du jour',
    imageZoom: 1,
    imageBrightness: 100,
    customOverlayOpacity: 0.45,
    scheduledTime: '2026-09-30T18:00',
  },
  {
    id: 'slide-4',
    number: 4,
    text: "Simplifiez sans compromis jusqu'à ce qu'il ne reste que la pure quintessence.",
    kicker: 'DESIGN ÉPURÉ',
    subtitle: 'Épisode 04 · Studio Journal',
    imageUrl: PRESET_IMAGES.craft,
    imageAlt: 'Vase céramique artisanal sur pierre travertine',
    imageZoom: 1,
    imageBrightness: 100,
    customOverlayOpacity: 0.45,
    scheduledTime: '2026-10-01T09:00',
  },
  {
    id: 'slide-5',
    number: 5,
    text: "Construisez pour traverser les époques, pas seulement pour capter l'attention éphémère.",
    kicker: 'IMPACT DURABLE',
    subtitle: 'Épisode 05 · Studio Journal',
    imageUrl: PRESET_IMAGES.structure,
    imageAlt: 'Sculpture d acier et de verre sous ciel crépusculaire',
    imageZoom: 1,
    imageBrightness: 100,
    customOverlayOpacity: 0.45,
    scheduledTime: '2026-10-02T12:00',
  },
  {
    id: 'slide-6',
    number: 6,
    text: "L'innovation émerge toujours à l'intersection exacte de la passion et de la rigueur.",
    kicker: 'FUTUR & CULTURE',
    subtitle: 'Épisode 06 · Studio Journal',
    imageUrl: PRESET_IMAGES.skyline,
    imageAlt: 'Horizon urbain et reflets dorés',
    imageZoom: 1,
    imageBrightness: 100,
    customOverlayOpacity: 0.45,
    scheduledTime: '2026-10-03T17:30',
  },
];

export const INITIAL_TYPOGRAPHY: TypographyConfig = {
  fontStyle: 'editorial',
  boxStyle: 'scrim',
  position: 'bottom',
  align: 'left',
  fontSize: 1.1,
  textColor: '#ffffff',
  accentColor: '#6366f1',
  showKicker: true,
  showSubtitle: true,
  showSlideNumber: true,
  scrimOpacity: 0.7,
};

export const INITIAL_LOGO: LogoConfig = {
  enabled: true,
  type: 'predefined',
  predefinedId: 'studio-minimal',
  brandText: 'STUDIO HORIZON',
  brandHandle: '@studio.horizon',
  position: 'top-left',
  size: 'medium',
  opacity: 0.95,
  theme: 'white',
};

export const INITIAL_GRADIENT_BLUR = {
  enabled: false,
  direction: 'bottom' as const,
  blurAmount: 12,
};

export const COLOR_FILTER_PRESETS = [
  {
    id: 'sunset-gold' as const,
    name: 'Sunset Gold',
    colorStart: '#f59e0b',
    colorEnd: '#7c3aed',
    angle: 135,
    blendMode: 'overlay' as const,
    opacity: 0.55,
  },
  {
    id: 'cyber-noir' as const,
    name: 'Cyber Teal',
    colorStart: '#0284c7',
    colorEnd: '#10b981',
    angle: 135,
    blendMode: 'overlay' as const,
    opacity: 0.5,
  },
  {
    id: 'warm-travertine' as const,
    name: 'Warm Amber',
    colorStart: '#ea580c',
    colorEnd: '#fde047',
    angle: 180,
    blendMode: 'soft-light' as const,
    opacity: 0.6,
  },
  {
    id: 'deep-indigo' as const,
    name: 'Deep Indigo',
    colorStart: '#4338ca',
    colorEnd: '#06b6d4',
    angle: 45,
    blendMode: 'multiply' as const,
    opacity: 0.55,
  },
  {
    id: 'rose-quartz' as const,
    name: 'Rose Quartz',
    colorStart: '#f43f5e',
    colorEnd: '#a855f7',
    angle: 90,
    blendMode: 'overlay' as const,
    opacity: 0.5,
  },
  {
    id: 'emerald-forest' as const,
    name: 'Emerald Mist',
    colorStart: '#047857',
    colorEnd: '#0284c7',
    angle: 135,
    blendMode: 'overlay' as const,
    opacity: 0.5,
  },
  {
    id: 'monochrome' as const,
    name: 'Film Noir',
    colorStart: '#000000',
    colorEnd: '#ffffff',
    angle: 180,
    blendMode: 'color' as const,
    opacity: 0.8,
  },
  {
    id: 'neon-violet' as const,
    name: 'Néon Violet',
    colorStart: '#8b5cf6',
    colorEnd: '#ec4899',
    angle: 135,
    blendMode: 'overlay' as const,
    opacity: 0.55,
  },
  {
    id: 'peach-sunset' as const,
    name: 'Pêche Sunset',
    colorStart: '#fb923c',
    colorEnd: '#f43f5e',
    angle: 120,
    blendMode: 'soft-light' as const,
    opacity: 0.6,
  },
  {
    id: 'cyber-pink' as const,
    name: 'Cyberpunk',
    colorStart: '#06b6d4',
    colorEnd: '#d946ef',
    angle: 60,
    blendMode: 'overlay' as const,
    opacity: 0.55,
  },
];

export const INITIAL_COLOR_FILTER = {
  enabled: false,
  preset: 'none' as const,
  colorStart: '#f59e0b',
  colorEnd: '#7c3aed',
  angle: 135,
  opacity: 0.5,
  blendMode: 'overlay' as const,
};

